- hosts: all
  become: yes
  gather_facts: false
  tasks:
  - name: Execute a command apt update
      shell: apt update
  - name: Execute a command apt update
      shell: apt install nodejs
  - name: Execute a command apt update
      shell: nodejs -v
  - name: Execute a command apt update
      shell: apt install npm