- hosts: [inventory.hosts]
  become: true
  tasks:
    - name: docker pull example
      remote user: ubuntu
      shell: docker pull "{{ var_docker_repo }}"/"{{ var_job_name }}":"{{ var_build_number }}"

