- hosts: all
  become: yes
  gather_facts: false
  tasks:
  - name: Execute a command apt update
    command: apt-get install curl
    ignore errors: yes

  - name: Execute a command apt update
    command: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
    ignore errors: yes

  - name: Execute a command apt update
    command: apt-get install nodejs
    ignore errors: yes
    
  - name: Execute a command apt update
    command: node -v