- hosts: all
  become: yes
  gather_facts: false
  tasks:
  - name: Execute a command apt update
      shell: apt-get install curl
  - name: Execute a command apt update
      shell: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  - name: Execute a command apt update
      shell: apt-get install nodejs
  - name: Execute a command apt update
      shell: node -v